global:
  imagePullPolicy: Always

ingress:
  alb: false

persistence:
  ebs: false

pulsar:
  namespace: pulsar
  namespaceCreate: true
  components:
    proxy: false
  zookeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  broker:
    replicaCount: 1
    podMonitor:
      enabled: false
  bookkeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  autorecovery:
    podMonitor:
      enabled: false
  proxy:
    podMonitor:
      enabled: false
  kube-prometheus-stack:
    enabled: false
    prometheusOperator:
      enabled: false
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      enabled: false

postgresql:
  namespaceOverride: postgresql
  auth:
    username: postgres
    password: postgres
  primary:
    initdb:
      scripts:
        create-dbs.sql: |
          CREATE DATABASE auth;
          CREATE DATABASE products;
          CREATE DATABASE jobs;

jobs:
  enabled: true
  replicas: 1
  image: '905418201315.dkr.ecr.us-east-1.amazonaws.com/jobber/jobs:latest'
  port:
    http: 3001
    grpc: 5002

executor:
  enabled: true
  replicas: 1
  image: '905418201315.dkr.ecr.us-east-1.amazonaws.com/jobber/executor:latest'
  port: 3002

auth:
  enabled: true
  replicas: 1
  image: '905418201315.dkr.ecr.us-east-1.amazonaws.com/jobber/auth:latest'
  port:
    http: 3000
    grpc: 5000
  jwt:
    secret: 31FDUHHUdaXYQeN2jiofyPTnIGSjGbFP
    expirationMs: "28800000"
    secure: false

products:
  enabled: true
  replicas: 1
  image: '905418201315.dkr.ecr.us-east-1.amazonaws.com/jobber/products:latest'
  port:
    http: 3003
    grpc: 5001