global:
  imagePullPolicy: Always
  pulsarServiceUrl: pulsar://{{ .Release.Name }}-pulsar-broker.pulsar.svc.cluster.local:6650

pulsar:
  namespace: pulsar
  namespaceCreate: true
  volumes:
    persistence: false
  zookeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  broker:
    replicaCount: 1
    podMonitor:
      enabled: false
  bookkeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  autorecovery:
    podMonitor:
      enabled: false
  proxy:
    replicaCount: 1
    podMonitor:
      enabled: false
  kube-prometheus-stack:
    enabled: false
    prometheusOperator:
      enabled: false
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      enabled: false

postgresql:
  namespaceOverride: postgresql

jobs:
  enabled: true
  image: '905418201315.dkr.ecr.us-east-1.amazonaws.com/jobber/jobs:latest'
  port: 3001
  replicas: 1

executor:
  enabled: true
  image: '905418201315.dkr.ecr.us-east-1.amazonaws.com/jobber/executor:latest'
  port: 4000
  replicas: 1

auth:
  enabled: true
  image: '905418201315.dkr.ecr.us-east-1.amazonaws.com/jobber/auth:latest'
  port:
    http: 3000
    grpc: 5000
  replicas: 1
  jwt:
    secret: FOO_BAR
    expirationMs: 300000
