{{- if .Values.jobs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: jobs-http
  labels:
    app: jobs
spec:
  type: ClusterIP
  selector:
    app: jobs
  ports:
    - protocol: TCP
      port: {{ .Values.jobs.port.http }}
      targetPort: {{ .Values.jobs.port.http }}
{{- end }}